# Define Parameters #

ProgVer="0.1.3"

DefaultCase="OldDefault"

# Define Folders #

ProgDir="$(pwd)"
ConfigDir="$(ProgDir)/config"
FunctionsDir="$(ProgDir)/functions"
ProfileDir="$(ProgDir)/profiles"


